services:
  db:
    volumes: []

  backend:
    restart: "no"
    command: ["npm", "run", "start"]
    volumes: []
    environment:
      CHOKIDAR_USEPOLLING: "false"

  frontend:
    restart: "no"
    command: >-
      sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 5173"
    volumes: []
